// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Single source of truth for the Supabase origin. Everything else in the app
// (REST, edge functions, realtime WebSockets, the auth health panel) derives
// from these rather than hardcoding the project ref, so moving to a custom
// domain — e.g. https://auth.commodity-hub.eu, so users signing in with
// Google don't see a random-looking *.supabase.co URL and assume it's a scam
// — is a change to .env, not a hunt through the codebase.
// See docs/SUPABASE_CUSTOM_DOMAIN.md for the full migration checklist,
// including the parts that live outside this repo (DB cron jobs, RevenueCat
// webhook, Google Cloud Console redirect URIs, the static landing pages).
export const SUPABASE_URL =
  (import.meta.env.VITE_SUPABASE_URL as string | undefined) ??
  "https://kcxhsmlqqyarhlmcapmj.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjeGhzbWxxcXlhcmhsbWNhcG1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODM0MDcsImV4cCI6MjA2MTM1OTQwN30.qC25iAjNhbPVotryl7GONMgYkvg0DzEYp8uxioWzkfs";

/** Base URL for edge functions, e.g. `${SUPABASE_FUNCTIONS_URL}/health-check`. */
export const SUPABASE_FUNCTIONS_URL = `${SUPABASE_URL}/functions/v1`;

/** Same as SUPABASE_FUNCTIONS_URL but over WebSocket, for streaming functions. */
export const SUPABASE_FUNCTIONS_WS_URL = SUPABASE_FUNCTIONS_URL.replace(/^http/, 'ws');

// NOTE: deliberately NOT derived from SUPABASE_URL. This is the localStorage
// key holding existing users' sessions — changing it (as would happen if it
// tracked a new custom domain) silently signs out everyone who is currently
// logged in. It is tied to the project ref, which a custom domain does not
// change, so it stays pinned even after the domain moves.
export const SUPABASE_AUTH_STORAGE_KEY = 'sb-kcxhsmlqqyarhlmcapmj-auth-token';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

type StoredAuthInspection = {
  found: boolean;
  valid: boolean;
  reason?: string;
};

const isAuthSessionStorageKey = (key: string) => {
  if (key.endsWith('-code-verifier')) return false;
  return (
    key === SUPABASE_AUTH_STORAGE_KEY ||
    key === 'supabase.auth.token' ||
    (key.startsWith('sb-') && key.endsWith('-auth-token'))
  );
};

const decodeJwtPayload = (token: string): Record<string, unknown> | null => {
  try {
    const payload = token.split('.')[1];
    if (!payload) return null;
    const normalized = payload.replace(/-/g, '+').replace(/_/g, '/');
    const padded = normalized.padEnd(normalized.length + ((4 - (normalized.length % 4)) % 4), '=');
    return JSON.parse(atob(padded));
  } catch {
    return null;
  }
};

const getStoredAccessToken = (raw: string): string | null => {
  try {
    const parsed = JSON.parse(raw);
    return (
      parsed?.access_token ??
      parsed?.currentSession?.access_token ??
      parsed?.session?.access_token ??
      null
    );
  } catch {
    return null;
  }
};

export const inspectSupabaseAuthStorage = (): StoredAuthInspection => {
  if (typeof window === 'undefined') return { found: false, valid: false };

  try {
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (!key || !isAuthSessionStorageKey(key)) continue;

      const raw = localStorage.getItem(key);
      if (!raw) continue;

      const token = getStoredAccessToken(raw);
      if (!token) return { found: true, valid: false, reason: 'Malformed auth session' };

      const payload = decodeJwtPayload(token);
      if (!payload) return { found: true, valid: false, reason: 'Token not decodable' };
      if (!payload.sub) return { found: true, valid: false, reason: 'Missing sub claim' };

      return { found: true, valid: true };
    }
  } catch {
    return { found: false, valid: false, reason: 'localStorage unavailable' };
  }

  return { found: false, valid: false };
};

// Guard: clear malformed Supabase auth sessions left in localStorage from
// previous sessions. A token without a `sub` claim causes /auth/v1/user to
// return 403 ("invalid claim: missing sub claim"), which breaks sign-in
// (including Google OAuth callbacks) until the bad session is removed. OAuth
// PKCE code-verifier entries are intentionally ignored because they are not
// sessions and should never be reported as invalid auth tokens.
export const purgeMalformedSupabaseTokens = (): number => {
  if (typeof window === 'undefined') return 0;
  let removed = 0;
  try {
    const keys: string[] = [];
    for (let i = 0; i < localStorage.length; i++) {
      const k = localStorage.key(i);
      if (k && isAuthSessionStorageKey(k)) keys.push(k);
    }
    for (const k of keys) {
      const raw = localStorage.getItem(k);
      if (!raw) continue;
      try {
        const parsed = JSON.parse(raw);
        const token: string | undefined =
          parsed?.access_token ?? parsed?.currentSession?.access_token ?? parsed?.session?.access_token;

        // Only remove entries that actually contain a token we can decode
        // AND that token is malformed (e.g. missing `sub`). Without a token
        // present, the entry may be a transient helper value the Supabase
        // client manages itself — leave it alone.
        if (typeof token !== 'string') continue;
        if (token.split('.').length !== 3) {
          localStorage.removeItem(k);
          removed++;
          continue;
        }
        const payload = decodeJwtPayload(token);
        if (!payload?.sub) {
          localStorage.removeItem(k);
          removed++;
          console.warn('Cleared malformed Supabase auth session');
        }
      } catch {
        // Unparseable JSON in an auth storage slot — safe to remove.
        localStorage.removeItem(k);
        removed++;
      }
    }
  } catch {
    // localStorage unavailable — ignore
  }
  return removed;
};

// Run once at module load so a bad token from a prior session never reaches
// the Supabase client during boot.
purgeMalformedSupabaseTokens();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    storageKey: SUPABASE_AUTH_STORAGE_KEY,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});

/**
 * Native OAuth must not depend on PKCE code-verifier storage because Android
 * opens Google in Chrome Custom Tabs while the app WebView is backgrounded.
 * The main app client stays on PKCE for web, while this throwaway client only
 * builds an implicit-flow provider URL for native sign-in. The returned
 * access/refresh tokens are then persisted with the main `supabase` client via
 * `setSession()` when the app receives the deep link.
 *
 * This pattern only works because the *consumer* of the resulting tokens
 * (setSession(), a direct call) doesn't care about flow type. It would NOT
 * work for a page-load-style redirect landing on the main app client: that
 * client auto-detects the URL via detectSessionInUrl, which explicitly
 * rejects a mismatched flow type (an implicit-style link lands on a
 * flowType:'pkce' client → AuthPKCEGrantCodeExchangeError, thrown, not
 * silently ignored — see @supabase/auth-js GoTrueClient._getSessionFromURL).
 * That's why this can't be reused to fix email-link flows (signUp/
 * resetPasswordForEmail confirmation links, which land as a normal page
 * load on the shared PKCE client) — see AuthConfirm.tsx for how those are
 * actually fixed instead (verifyOtp with a token_hash, which needs no
 * locally-stored verifier at all).
 */
export const createNativeImplicitOAuthClient = () => createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
      flowType: 'implicit',
    },
  },
);